backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/media'
public_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'post/{{fields.path}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    preview_path: '{{fields.path}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'string' }
      - {
          label: 'AllowComment',
          name: 'allowComment',
          widget: 'boolean',
          default: false,
        }
